import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Markdown File Renamer Web App",
  description: "Generated by create next app",
  creator: "https://github.com/sametcn99",
  keywords:
    "nextjs, typescript, tailwindcss, markdown, md, mdx, renamer, web app, file renamer, file renamer web app, markdown file renamer",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col justify-center items-center py-20 space-y-2 min-h-screen">
          {children}
        <Footer />
        </main>
        <Analytics />
      </body>
    </html>
  );
}
